"""
Variable catalog for Swiss Federal Statistics Office hectare-level datasets.

Each dict maps variable code → English description (translated from German source).
Comment out unwanted variables with '#' — get_selected_columns() returns only uncommented ones.

Aggregation hints in AGG_HINTS: "sum" for absolute counts, "mean" for rates/ratios,
"max" for categorical codes, "sum" is the default.
"""

# ---------------------------------------------------------------------------
# STATPOP — Population and Household Statistics (from 2010)
# Source: statpop-population_variables_german.xlsx
# All variables are counts per hectare → aggregate with "sum"
# ---------------------------------------------------------------------------
STATPOP_VARIABLES: dict[str, str] = {
    # --- Total population ---
    "BBTOT": "Permanent resident population, total",
    # --- By nationality ---
    "BB11": "Swiss nationals",
    "BB12": "Foreign nationals, total",
    "BB13": "EU/EFTA nationals",
    "BB14": "Other European nationals",
    "BB15": "Non-European nationals",
    "BB16": "Nationality unknown or unassignable",
    # --- By birthplace ---
    "BB21": "Born in Switzerland, total",
    "BB22": "Born in municipality of residence",
    "BB23": "Born in same canton",
    "BB24": "Born in another canton",
    "BB25": "Born in Switzerland, municipality unassignable",
    "BB26": "Born abroad, total",
    "BB27": "Born in EU/EFTA country",
    "BB28": "Born in other European country",
    "BB29": "Born in non-European country",
    "BB30": "Born abroad, country unknown or unassignable",
    # --- Male population by age group ---
    "BBMTOT": "Male permanent resident population, total",
    "BBM01": "Male, 0–4 years",
    "BBM02": "Male, 5–9 years",
    "BBM03": "Male, 10–14 years",
    "BBM04": "Male, 15–19 years",
    "BBM05": "Male, 20–24 years",
    "BBM06": "Male, 25–29 years",
    "BBM07": "Male, 30–34 years",
    "BBM08": "Male, 35–39 years",
    "BBM09": "Male, 40–44 years",
    "BBM10": "Male, 45–49 years",
    "BBM11": "Male, 50–54 years",
    "BBM12": "Male, 55–59 years",
    "BBM13": "Male, 60–64 years",
    "BBM14": "Male, 65–69 years",
    "BBM15": "Male, 70–74 years",
    "BBM16": "Male, 75–79 years",
    "BBM17": "Male, 80–84 years",
    "BBM18": "Male, 85–89 years",
    "BBM19": "Male, 90+ years",
    # --- Female population by age group ---
    "BBWTOT": "Female permanent resident population, total",
    "BBW01": "Female, 0–4 years",
    "BBW02": "Female, 5–9 years",
    "BBW03": "Female, 10–14 years",
    "BBW04": "Female, 15–19 years",
    "BBW05": "Female, 20–24 years",
    "BBW06": "Female, 25–29 years",
    "BBW07": "Female, 30–34 years",
    "BBW08": "Female, 35–39 years",
    "BBW09": "Female, 40–44 years",
    "BBW10": "Female, 45–49 years",
    "BBW11": "Female, 50–54 years",
    "BBW12": "Female, 55–59 years",
    "BBW13": "Female, 60–64 years",
    "BBW14": "Female, 65–69 years",
    "BBW15": "Female, 70–74 years",
    "BBW16": "Female, 75–79 years",
    "BBW17": "Female, 80–84 years",
    "BBW18": "Female, 85–89 years",
    "BBW19": "Female, 90+ years",
    # --- Duration of residence in municipality ---
    "BB41": "Less than 1 year in municipality",
    "BB42": "1–5 years in municipality",
    "BB43": "6–10 years in municipality",
    "BB44": "More than 10 years in municipality",
    "BB45": "Since birth in municipality",
    "BB46": "Duration of residence unknown",
    # --- Previous residence (1 year ago) ---
    "BB51": "Same municipality as today",
    "BB52": "Same canton",
    "BB53": "Different canton",
    "BB54": "Abroad",
    "BB55": "Not yet born",
    "BB56": "Unassignable or unknown",
    # --- Private households (from 2012) ---
    "HPTOT": "Private households, total",
    "HP01": "Households with 1 person",
    "HP02": "Households with 2 persons",
    "HP03": "Households with 3 persons",
    "HP04": "Households with 4 persons",
    "HP05": "Households with 5 persons",
    "HP06": "Households with 6+ persons",
    "HPI": "Household plausibility class (1=plausible, 2=contains implausible)",
}

# ---------------------------------------------------------------------------
# BDS — Buildings and Dwellings Statistics (from 2010)
# Source: bds-buildings_dwellings_variables_german.xlsx
# All variables are counts per hectare → aggregate with "sum"
# Exceptions: GTF, WTF, WT1F–WT6F are areas (m²) → also "sum"
# ---------------------------------------------------------------------------
BDS_VARIABLES: dict[str, str] = {
    # --- Residential buildings total ---
    "GTOT": "Residential buildings, total",
    "GA01": "Residential buildings, total (all types)",
    "GA02": "Purely residential buildings",
    "GA03": "Single-family houses",
    "GA05": "Multi-family houses",
    "GA06": "Residential buildings with secondary use",
    "GA07": "Buildings with partial residential use",
    "GA08": "Temporary accommodations (from 2012)",
    # --- Residential buildings by construction period ---
    "GB01": "Built before 1919",
    "GB02": "Built 1919–1945",
    "GB03": "Built 1946–1960",
    "GB04": "Built 1961–1970",
    "GB05": "Built 1971–1980",
    "GB06": "Built 1981–1990",
    "GB07": "Built 1991–1995",
    "GB08": "Built 1996–2000",
    "GB09": "Built 2001–2005",
    "GB10": "Built 2006–2010",
    "GB11": "Built 2011–2015",
    "GB12": "Built 2016–2020",
    "GB13": "Built 2021–2023",
    # --- Residential buildings by number of storeys ---
    "GG01": "1 storey",
    "GG02": "2 storeys",
    "GG03": "3 storeys",
    "GG04": "4 storeys",
    "GG05": "5 storeys",
    "GG06": "6 storeys",
    "GG07": "7–9 storeys",
    "GG08": "10–14 storeys",
    "GG09": "15+ storeys",
    # --- Main heat generator for heating (from 2021) ---
    "GH21": "Heat pump (heating)",
    "GH22": "Thermal solar system (heating)",
    "GH23": "Boiler (heating)",
    "GH24": "Stove (heating)",
    "GH25": "Electric heating",
    "GH26": "Heat exchanger (heating)",
    "GH27": "Combined heat and power (heating)",
    "GH28": "Other heat generator (heating)",
    "GH29": "No heat generator (heating)",
    # --- Main energy source for heating (from 2021) ---
    "GE21": "Air (heating energy)",
    "GE22": "Geothermal (heating energy)",
    "GE23": "Water — groundwater/surface/wastewater (heating energy)",
    "GE24": "Gas (heating energy)",
    "GE25": "Heating oil (heating energy)",
    "GE26": "Wood (heating energy)",
    "GE27": "Electricity (heating energy)",
    "GE28": "Solar thermal (heating energy)",
    "GE29": "District heating (heating energy)",
    "GE30": "Undetermined energy source (heating)",
    "GE31": "Other energy source (heating)",
    "GE32": "No energy source (heating)",
    # --- Main heat generator for hot water (from 2021) ---
    "GWW21": "Heat pump (hot water)",
    "GWW22": "Thermal solar system (hot water)",
    "GWW23": "Boiler (hot water)",
    "GWW24": "Boiler/tank (hot water)",
    "GWW25": "Heat exchanger (hot water)",
    "GWW26": "Combined heat and power (hot water)",
    "GWW27": "Other heat generator (hot water)",
    "GWW28": "No heat generator (hot water)",
    # --- Main energy source for hot water (from 2021) ---
    "GWE21": "Air (hot water energy)",
    "GWE22": "Geothermal (hot water energy)",
    "GWE23": "Water — groundwater/surface/wastewater (hot water energy)",
    "GWE24": "Gas (hot water energy)",
    "GWE25": "Heating oil (hot water energy)",
    "GWE26": "Wood (hot water energy)",
    "GWE27": "Electricity (hot water energy)",
    "GWE28": "Solar thermal (hot water energy)",
    "GWE29": "District heating (hot water energy)",
    "GWE30": "Undetermined energy source (hot water)",
    "GWE31": "Other energy source (hot water)",
    "GWE32": "No energy source (hot water)",
    # --- Buildings by number of dwellings ---
    "GW00": "Buildings with 0 dwellings",
    "GW01": "Buildings with 1 dwelling",
    "GW02": "Buildings with 2 dwellings",
    "GW03": "Buildings with 3 dwellings",
    "GW04": "Buildings with 4 dwellings",
    "GW05": "Buildings with 5 dwellings",
    "GW06": "Buildings with 6 dwellings",
    "GW07": "Buildings with 7–9 dwellings",
    "GW10": "Buildings with 10+ dwellings",
    # --- Dwellings total and by construction period ---
    "WTOT": "Dwellings, total",
    "WTF": "Total residential floor area (m²)",
    "WT01": "Dwellings built before 1919",
    "WT02": "Dwellings built 1919–1945",
    "WT03": "Dwellings built 1946–1960",
    "WT04": "Dwellings built 1961–1970",
    "WT05": "Dwellings built 1971–1980",
    "WT06": "Dwellings built 1981–1990",
    "WT07": "Dwellings built 1991–1995",
    "WT08": "Dwellings built 1996–2000",
    "WT09": "Dwellings built 2001–2005",
    "WT10": "Dwellings built 2006–2010",
    "WT11": "Dwellings built 2011–2015",
    "WT12": "Dwellings built 2016–2020",
    "WT13": "Dwellings built 2021–2023",
    # --- Dwellings with 1 room ---
    "WT1": "Dwellings with 1 room",
    "WT1F": "Floor area, 1-room dwellings (m²)",
    "WT101": "1-room dwellings, built before 1919",
    "WT102": "1-room dwellings, built 1919–1945",
    "WT103": "1-room dwellings, built 1946–1960",
    "WT104": "1-room dwellings, built 1961–1970",
    "WT105": "1-room dwellings, built 1971–1980",
    "WT106": "1-room dwellings, built 1981–1990",
    "WT107": "1-room dwellings, built 1991–1995",
    "WT108": "1-room dwellings, built 1996–2000",
    "WT109": "1-room dwellings, built 2001–2005",
    "WT110": "1-room dwellings, built 2006–2010",
    "WT111": "1-room dwellings, built 2011–2015",
    "WT112": "1-room dwellings, built 2016–2020",
    "WT113": "1-room dwellings, built 2021–2023",
    # --- Dwellings with 2 rooms ---
    "WT2": "Dwellings with 2 rooms",
    "WT2F": "Floor area, 2-room dwellings (m²)",
    "WT201": "2-room dwellings, built before 1919",
    "WT202": "2-room dwellings, built 1919–1945",
    "WT203": "2-room dwellings, built 1946–1960",
    "WT204": "2-room dwellings, built 1961–1970",
    "WT205": "2-room dwellings, built 1971–1980",
    "WT206": "2-room dwellings, built 1981–1990",
    "WT207": "2-room dwellings, built 1991–1995",
    "WT208": "2-room dwellings, built 1996–2000",
    "WT209": "2-room dwellings, built 2001–2005",
    "WT210": "2-room dwellings, built 2006–2010",
    "WT211": "2-room dwellings, built 2011–2015",
    "WT212": "2-room dwellings, built 2016–2020",
    "WT213": "2-room dwellings, built 2021–2023",
    # --- Dwellings with 3 rooms ---
    "WT3": "Dwellings with 3 rooms",
    "WT3F": "Floor area, 3-room dwellings (m²)",
    "WT301": "3-room dwellings, built before 1919",
    "WT302": "3-room dwellings, built 1919–1945",
    "WT303": "3-room dwellings, built 1946–1960",
    "WT304": "3-room dwellings, built 1961–1970",
    "WT305": "3-room dwellings, built 1971–1980",
    "WT306": "3-room dwellings, built 1981–1990",
    "WT307": "3-room dwellings, built 1991–1995",
    "WT308": "3-room dwellings, built 1996–2000",
    "WT309": "3-room dwellings, built 2001–2005",
    "WT310": "3-room dwellings, built 2006–2010",
    "WT311": "3-room dwellings, built 2011–2015",
    "WT312": "3-room dwellings, built 2016–2020",
    "WT313": "3-room dwellings, built 2021–2023",
    # --- Dwellings with 4 rooms ---
    "WT4": "Dwellings with 4 rooms",
    "WT4F": "Floor area, 4-room dwellings (m²)",
    "WT401": "4-room dwellings, built before 1919",
    "WT402": "4-room dwellings, built 1919–1945",
    "WT403": "4-room dwellings, built 1946–1960",
    "WT404": "4-room dwellings, built 1961–1970",
    "WT405": "4-room dwellings, built 1971–1980",
    "WT406": "4-room dwellings, built 1981–1990",
    "WT407": "4-room dwellings, built 1991–1995",
    "WT408": "4-room dwellings, built 1996–2000",
    "WT409": "4-room dwellings, built 2001–2005",
    "WT410": "4-room dwellings, built 2006–2010",
    "WT411": "4-room dwellings, built 2011–2015",
    "WT412": "4-room dwellings, built 2016–2020",
    "WT413": "4-room dwellings, built 2021–2023",
    # --- Dwellings with 5 rooms ---
    "WT5": "Dwellings with 5 rooms",
    "WT5F": "Floor area, 5-room dwellings (m²)",
    "WT501": "5-room dwellings, built before 1919",
    "WT502": "5-room dwellings, built 1919–1945",
    "WT503": "5-room dwellings, built 1946–1960",
    "WT504": "5-room dwellings, built 1961–1970",
    "WT505": "5-room dwellings, built 1971–1980",
    "WT506": "5-room dwellings, built 1981–1990",
    "WT507": "5-room dwellings, built 1991–1995",
    "WT508": "5-room dwellings, built 1996–2000",
    "WT509": "5-room dwellings, built 2001–2005",
    "WT510": "5-room dwellings, built 2006–2010",
    "WT511": "5-room dwellings, built 2011–2015",
    "WT512": "5-room dwellings, built 2016–2020",
    "WT513": "5-room dwellings, built 2021–2023",
    # --- Dwellings with 6+ rooms ---
    "WT6": "Dwellings with 6+ rooms",
    "WT6F": "Floor area, 6+-room dwellings (m²)",
    "WT601": "6+-room dwellings, built before 1919",
    "WT602": "6+-room dwellings, built 1919–1945",
    "WT603": "6+-room dwellings, built 1946–1960",
    "WT604": "6+-room dwellings, built 1961–1970",
    "WT605": "6+-room dwellings, built 1971–1980",
    "WT606": "6+-room dwellings, built 1981–1990",
    "WT607": "6+-room dwellings, built 1991–1995",
    "WT608": "6+-room dwellings, built 1996–2000",
    "WT609": "6+-room dwellings, built 2001–2005",
    "WT610": "6+-room dwellings, built 2006–2010",
    "WT611": "6+-room dwellings, built 2011–2015",
    "WT612": "6+-room dwellings, built 2016–2020",
    "WT613": "6+-room dwellings, built 2021–2023",
}

# ---------------------------------------------------------------------------
# SLS — Land Use Statistics (nomenclature 2004)
# Source: sls-landuse_variables_german.xlsx
# Column names follow the pattern: {TYPE}{PERIOD}_{CLASSES}
#   TYPE: LU (land use), AS (area statistics), LC (land cover), FJ (survey year)
#   PERIOD: 85, 97, 09, 18, 25
#   CLASSES: 4, 10, 17, 27, 46 (LU/AS), 6, 27 (LC)
# These are categorical codes per hectare → aggregate with "max" (mode)
# ---------------------------------------------------------------------------
SLS_VARIABLES: dict[str, str] = {
    # --- Survey year per hectare ---
    "FJ85": "Exact survey year, period 1979/85",
    "FJ97": "Exact survey year, period 1992/97",
    "FJ09": "Exact survey year, period 2004/09",
    "FJ18": "Exact survey year, period 2013/18",
    "FJ25": "Exact survey year, period 2018/25",
    # --- Land use, 4 classes (1=Settlement, 2=Agriculture, 3=Forest, 4=Unproductive) ---
    "LU85_4": "Land use 1979/85, 4 classes",
    "LU97_4": "Land use 1992/97, 4 classes",
    "LU09_4": "Land use 2004/09, 4 classes",
    "LU18_4": "Land use 2013/18, 4 classes",
    "LU25_4": "Land use 2018/25, 4 classes",
    # --- Land use, 10 classes ---
    "LU85_10": "Land use 1979/85, 10 classes",
    "LU97_10": "Land use 1992/97, 10 classes",
    "LU09_10": "Land use 2004/09, 10 classes",
    "LU18_10": "Land use 2013/18, 10 classes",
    "LU25_10": "Land use 2018/25, 10 classes",
    # --- Land use, 46 classes (most detailed) ---
    "LU85_46": "Land use 1979/85, 46 classes",
    "LU97_46": "Land use 1992/97, 46 classes",
    "LU09_46": "Land use 2004/09, 46 classes",
    "LU18_46": "Land use 2013/18, 46 classes",
    "LU25_46": "Land use 2018/25, 46 classes",
    # --- Land cover, 6 classes (from 1979/85) ---
    "LC85_6": "Land cover 1979/85, 6 classes",
    "LC97_6": "Land cover 1992/97, 6 classes",
    "LC09_6": "Land cover 2004/09, 6 classes",
    "LC18_6": "Land cover 2013/18, 6 classes",
    "LC25_6": "Land cover 2018/25, 6 classes",
    # --- Land cover, 27 classes (from 1979/85) ---
    "LC85_27": "Land cover 1979/85, 27 classes",
    "LC97_27": "Land cover 1992/97, 27 classes",
    "LC09_27": "Land cover 2004/09, 27 classes",
    "LC18_27": "Land cover 2013/18, 27 classes",
    "LC25_27": "Land cover 2018/25, 27 classes",
    # --- Area Statistics (AS), 17 classes ---
    "AS85_17": "Area Statistics 1979/85, 17 classes",
    "AS97_17": "Area Statistics 1992/97, 17 classes",
    "AS09_17": "Area Statistics 2004/09, 17 classes",
    "AS18_17": "Area Statistics 2013/18, 17 classes",
    "AS25_17": "Area Statistics 2018/25, 17 classes",
}

# ---------------------------------------------------------------------------
# SLS class code lookups — numeric code → English label
# Each classification scheme has its own code space.
# Use: SLS_CLASS_LABELS["AS_17"][10] → "Forest (excl. shrub forest)"
# Source: sls-landuse_variables_german.xlsx, translated to English.
# ---------------------------------------------------------------------------

SLS_CLASS_LABELS: dict[str, dict[int, str]] = {
    # ----- Area Statistics (AS), 4 main domains -----
    "AS_4": {
        1: "Settlement areas",
        2: "Agricultural areas",
        3: "Wooded areas",
        4: "Unproductive areas",
    },
    # ----- Area Statistics (AS), 17 classes -----
    "AS_17": {
        1: "Industrial and commercial areas",
        2: "Building areas",
        3: "Transport areas",
        4: "Special settlement areas",
        5: "Recreation and green spaces",
        6: "Fruit, vine and horticultural areas",
        7: "Arable land",
        8: "Natural meadows and local pastures",
        9: "Alpine farming areas",
        10: "Forest (excl. shrub forest)",
        11: "Shrub forest",
        12: "Groves",
        13: "Standing water bodies",
        14: "Watercourses",
        15: "Unproductive vegetation",
        16: "Unvegetated areas",
        17: "Glaciers and firn",
    },
    # ----- Area Statistics (AS), 27 classes -----
    "AS_27": {
        1: "Industrial and commercial areas",
        2: "Residential areas",
        3: "Public building areas",
        4: "Agricultural building areas",
        5: "Unspecified building areas",
        6: "Road areas",
        7: "Railway areas",
        8: "Airport areas",
        9: "Special settlement areas",
        10: "Recreation and green spaces",
        11: "Fruit-growing areas",
        12: "Vineyard areas",
        13: "Horticultural areas",
        14: "Arable land",
        15: "Natural meadows",
        16: "Local pastures",
        17: "Alpine meadows",
        18: "Alpine and Jura pastures",
        19: "Closed forest",
        20: "Open forest",
        21: "Shrub forest",
        22: "Groves",
        23: "Lakes",
        24: "Watercourses",
        25: "Unproductive vegetation",
        26: "Unvegetated areas",
        27: "Glaciers and firn",
    },
    # ----- Area Statistics (AS), 72 basic categories -----
    "AS_72": {
        1: "Industrial and commercial buildings",
        2: "Surroundings of industrial/commercial buildings",
        3: "Single- and two-family houses",
        4: "Surroundings of single-/two-family houses",
        5: "Row and terrace houses",
        6: "Surroundings of row/terrace houses",
        7: "Multi-family houses",
        8: "Surroundings of multi-family houses",
        9: "Public buildings",
        10: "Surroundings of public buildings",
        11: "Agricultural buildings",
        12: "Surroundings of agricultural buildings",
        13: "Unspecified buildings",
        14: "Surroundings of unspecified buildings",
        15: "Motorways",
        16: "Motorway green areas",
        17: "Roads and paths",
        18: "Road green areas",
        19: "Parking areas",
        20: "Paved railway areas",
        21: "Railway green areas",
        22: "Airfields",
        23: "Grass runways and airfield green areas",
        24: "Energy supply installations",
        25: "Wastewater treatment plants",
        26: "Other supply and disposal installations",
        27: "Landfills",
        28: "Quarries and mines",
        29: "Construction sites",
        30: "Construction and settlement brownfields",
        31: "Public parks",
        32: "Sports facilities",
        33: "Golf courses",
        34: "Camping sites",
        35: "Allotment gardens",
        36: "Cemeteries",
        37: "Orchards (intensive)",
        38: "Standard fruit trees (extensive)",
        39: "Vineyards",
        40: "Horticulture areas",
        41: "Arable land",
        42: "Natural meadows",
        43: "Local pastures",
        44: "Overgrown meadows and local pastures",
        45: "Alpine meadows",
        46: "Favourable alpine and Jura pastures",
        47: "Overgrown alpine and Jura pastures",
        48: "Stony alpine and Jura pastures",
        49: "Sheep alps",
        50: "Normal forest",
        51: "Narrow forest",
        52: "Afforestations",
        53: "Forest clearings",
        54: "Forest damage",
        55: "Open forest (on agricultural land)",
        56: "Open forest (on unproductive land)",
        57: "Shrub forest",
        58: "Copses and hedges",
        59: "Tree clusters (on agricultural land)",
        60: "Tree clusters (on unproductive land)",
        61: "Standing water bodies",
        62: "Watercourses",
        63: "Flood control structures",
        64: "Scrub and shrub vegetation",
        65: "Unproductive grass and herb vegetation",
        66: "Avalanche and rockfall protection structures",
        67: "Wetlands",
        68: "Alpine sports infrastructure",
        69: "Rock",
        70: "Scree and sand",
        71: "Landscape interventions",
        72: "Glaciers and firn",
    },
    # ----- Land Cover (LC), 6 main domains -----
    "LC_6": {
        1: "Artificial surfaces",
        2: "Grass and herb vegetation",
        3: "Shrub vegetation",
        4: "Tree vegetation",
        5: "Unvegetated areas",
        6: "Water and wetlands",
    },
    # ----- Land Cover (LC), 27 classes -----
    "LC_27": {
        11: "Sealed surfaces",
        12: "Buildings",
        13: "Greenhouses",
        14: "Bed structures",
        15: "Lawns",
        16: "Trees on artificial surfaces",
        17: "Mixed small structures",
        21: "Grass and herb vegetation",
        31: "Scrub",
        32: "Overgrown areas",
        33: "Low-stem fruit trees",
        34: "Vines",
        35: "Horticultural permanent crops",
        41: "Closed tree stands",
        42: "Forest edges",
        43: "Forest strips",
        44: "Open tree stands",
        45: "Shrub forest stands",
        46: "Linear tree stands",
        47: "Tree clusters",
        51: "Exposed rock",
        52: "Loose rock",
        53: "Stony surfaces",
        61: "Water",
        62: "Glaciers and firn",
        63: "Wet sites",
        64: "Reed beds",
    },
    # ----- Land Use (LU), 4 main domains -----
    "LU_4": {
        1: "Settlement",
        2: "Agriculture",
        3: "Wooded areas",
        4: "Unproductive",
    },
    # ----- Land Use (LU), 10 classes -----
    "LU_10": {
        100: "Building areas",
        120: "Transport areas",
        140: "Special settlement areas",
        160: "Recreation and green spaces",
        200: "Fruit, vine and horticultural farming",
        220: "Arable and fodder farming",
        240: "Alpine farming",
        300: "Forest (excl. agricultural use)",
        400: "Lakes and rivers",
        420: "Unproductive land",
    },
    # ----- Land Use (LU), 46 basic categories -----
    "LU_46": {
        101: "Industrial and commercial areas > 1 ha",
        102: "Industrial and commercial areas < 1 ha",
        103: "Single- and two-family house areas",
        104: "Row and terrace house areas",
        105: "Multi-family house areas",
        106: "Public building areas",
        107: "Agricultural building areas",
        108: "Unspecified building areas",
        121: "Motorway areas",
        122: "Road areas",
        123: "Parking areas",
        124: "Railway areas",
        125: "Airport areas",
        141: "Energy supply installations",
        142: "Wastewater treatment plants",
        143: "Other supply and disposal installations",
        144: "Landfills",
        145: "Quarries and mines",
        146: "Construction sites",
        147: "Construction and settlement brownfields",
        161: "Public parks",
        162: "Sports facilities",
        163: "Golf courses",
        164: "Camping sites",
        165: "Allotment gardens",
        166: "Cemeteries",
        201: "Fruit farming",
        202: "Viticulture",
        203: "Horticulture",
        221: "Arable land (broad sense)",
        222: "Natural meadows (broad sense)",
        223: "Local pastures (broad sense)",
        241: "Alpine meadows (broad sense)",
        242: "Alpine and Jura pastures (broad sense)",
        243: "Sheep alps (broad sense)",
        301: "Forest stands",
        302: "Afforestations",
        303: "Forest clearings",
        304: "Forest damage",
        401: "Lakes",
        402: "Rivers and streams",
        403: "Flood control structures",
        421: "No use",
        422: "Avalanche and rockfall protection structures",
        423: "Alpine sports infrastructure",
        424: "Landscape interventions",
    },
}

# ---------------------------------------------------------------------------
# STATENT — Structural Business Statistics (from 2011)
# Source: statent-economy_variables_german.xlsx
# All variables are counts per hectare → aggregate with "sum"
# Privacy: values < 4 are set to 4 in the source data
# ---------------------------------------------------------------------------
STATENT_VARIABLES: dict[str, str] = {
    # --- Establishments and employees by economic sector ---
    "B08T": "Establishments, total",
    "B08S1": "Establishments, sector 1 (agriculture)",
    "B08S2": "Establishments, sector 2 (industry)",
    "B08S3": "Establishments, sector 3 (services)",
    "B08EMPT": "Employees, total",
    "B08EMPTS1": "Employees, sector 1",
    "B08EMPFS1": "Female employees, sector 1",
    "B08EMPMS1": "Male employees, sector 1",
    "B08EMPTS2": "Employees, sector 2",
    "B08EMPFS2": "Female employees, sector 2",
    "B08EMPMS2": "Male employees, sector 2",
    "B08EMPTS3": "Employees, sector 3",
    "B08EMPFS3": "Female employees, sector 3",
    "B08EMPMS3": "Male employees, sector 3",
    # --- Full-time equivalents by sector ---
    "B08VZAT": "Full-time equivalents (FTE), total",
    "B08VZATS1": "FTE, sector 1",
    "B08VZAFS1": "FTE female, sector 1",
    "B08VZAMS1": "FTE male, sector 1",
    "B08VZATS2": "FTE, sector 2",
    "B08VZAFS2": "FTE female, sector 2",
    "B08VZAMS2": "FTE male, sector 2",
    "B08VZATS3": "FTE, sector 3",
    "B08VZAFS3": "FTE female, sector 3",
    "B08VZAMS3": "FTE male, sector 3",
    # --- Public vs private sector ---
    "B08OFT": "Establishments, public sector",
    "B08PRT": "Establishments, private sector",
    "B08EMPOFT": "Employees, public sector total",
    "B08EMPOFF": "Employees, public sector female",
    "B08EMPOFM": "Employees, public sector male",
    "B08EMPPRT": "Employees, private sector total",
    "B08EMPPRF": "Employees, private sector female",
    "B08EMPPRM": "Employees, private sector male",
    "B08VZAOFT": "FTE, public sector total",
    "B08VZAOFF": "FTE, public sector female",
    "B08VZAOFM": "FTE, public sector male",
    "B08VZAPRT": "FTE, private sector total",
    "B08VZAPRF": "FTE, private sector female",
    "B08VZAPRM": "FTE, private sector male",
    # --- Market vs non-market oriented ---
    "B08NMT": "Establishments, non-market oriented",
    "B08UMT": "Establishments, market oriented",
    "B08EMPNMT": "Employees, non-market total",
    "B08EMPNMF": "Employees, non-market female",
    "B08EMPNMM": "Employees, non-market male",
    "B08EMPUMT": "Employees, market total",
    "B08EMPUMF": "Employees, market female",
    "B08EMPUMM": "Employees, market male",
    "B08VZANMT": "FTE, non-market total",
    "B08VZANMF": "FTE, non-market female",
    "B08VZANMM": "FTE, non-market male",
    "B08VZAUMT": "FTE, market total",
    "B08VZAUMF": "FTE, market female",
    "B08VZAUMM": "FTE, market male",
    # --- Establishments by NOGA division ---
    "B0801AS": "Establishments: Agriculture, hunting (NOGA 01)",
    "B0802AS": "Establishments: Forestry, logging (NOGA 02)",
    "B0803AS": "Establishments: Fishing, aquaculture (NOGA 03)",
    "B0805AS": "Establishments: Coal mining (NOGA 05)",
    "B0806AS": "Establishments: Oil and gas extraction (NOGA 06)",
    "B0807AS": "Establishments: Metal ore mining (NOGA 07)",
    "B0808AS": "Establishments: Other mining, quarrying (NOGA 08)",
    "B0809AS": "Establishments: Mining support services (NOGA 09)",
    "B0810AS": "Establishments: Food products (NOGA 10)",
    "B0811AS": "Establishments: Beverages (NOGA 11)",
    "B0812AS": "Establishments: Tobacco (NOGA 12)",
    "B0813AS": "Establishments: Textiles (NOGA 13)",
    "B0814AS": "Establishments: Wearing apparel (NOGA 14)",
    "B0815AS": "Establishments: Leather products (NOGA 15)",
    "B0816AS": "Establishments: Wood products (NOGA 16)",
    "B0817AS": "Establishments: Paper products (NOGA 17)",
    "B0818AS": "Establishments: Printing, media reproduction (NOGA 18)",
    "B0819AS": "Establishments: Coke, petroleum products (NOGA 19)",
    "B0820AS": "Establishments: Chemical products (NOGA 20)",
    "B0821AS": "Establishments: Pharmaceutical products (NOGA 21)",
    "B0822AS": "Establishments: Rubber and plastics (NOGA 22)",
    "B0823AS": "Establishments: Glass, ceramics, stone (NOGA 23)",
    "B0824AS": "Establishments: Basic metals (NOGA 24)",
    "B0825AS": "Establishments: Fabricated metals (NOGA 25)",
    "B0826AS": "Establishments: Computer, electronic, optical (NOGA 26)",
    "B0827AS": "Establishments: Electrical equipment (NOGA 27)",
    "B0828AS": "Establishments: Machinery (NOGA 28)",
    "B0829AS": "Establishments: Motor vehicles (NOGA 29)",
    "B0830AS": "Establishments: Other transport equipment (NOGA 30)",
    "B0831AS": "Establishments: Furniture (NOGA 31)",
    "B0832AS": "Establishments: Other manufactured goods (NOGA 32)",
    "B0833AS": "Establishments: Repair/installation of machinery (NOGA 33)",
    "B0835AS": "Establishments: Energy supply (NOGA 35)",
    "B0836AS": "Establishments: Water supply (NOGA 36)",
    "B0837AS": "Establishments: Sewerage (NOGA 37)",
    "B0838AS": "Establishments: Waste management, recycling (NOGA 38)",
    "B0839AS": "Establishments: Remediation (NOGA 39)",
    "B0841AS": "Establishments: Building construction (NOGA 41)",
    "B0842AS": "Establishments: Civil engineering (NOGA 42)",
    "B0843AS": "Establishments: Specialized construction (NOGA 43)",
    "B0845AS": "Establishments: Motor vehicle trade/repair (NOGA 45)",
    "B0846AS": "Establishments: Wholesale trade (NOGA 46)",
    "B0847AS": "Establishments: Retail trade (NOGA 47)",
    "B0849AS": "Establishments: Land transport (NOGA 49)",
    "B0850AS": "Establishments: Water transport (NOGA 50)",
    "B0851AS": "Establishments: Air transport (NOGA 51)",
    "B0852AS": "Establishments: Warehousing, transport support (NOGA 52)",
    "B0853AS": "Establishments: Postal, courier services (NOGA 53)",
    "B0855AS": "Establishments: Accommodation (NOGA 55)",
    "B0856AS": "Establishments: Food and beverage services (NOGA 56)",
    "B0858AS": "Establishments: Publishing (NOGA 58)",
    "B0859AS": "Establishments: Film, TV, music production (NOGA 59)",
    "B0860AS": "Establishments: Broadcasting (NOGA 60)",
    "B0861AS": "Establishments: Telecommunications (NOGA 61)",
    "B0862AS": "Establishments: IT services (NOGA 62)",
    "B0863AS": "Establishments: Information services (NOGA 63)",
    "B0864AS": "Establishments: Financial services (NOGA 64)",
    "B0865AS": "Establishments: Insurance, pensions (NOGA 65)",
    "B0866AS": "Establishments: Auxiliary financial services (NOGA 66)",
    "B0868AS": "Establishments: Real estate (NOGA 68)",
    "B0869AS": "Establishments: Legal, accounting (NOGA 69)",
    "B0870AS": "Establishments: Management consultancy (NOGA 70)",
    "B0871AS": "Establishments: Architecture, engineering (NOGA 71)",
    "B0872AS": "Establishments: R&D (NOGA 72)",
    "B0873AS": "Establishments: Advertising, market research (NOGA 73)",
    "B0874AS": "Establishments: Other professional services (NOGA 74)",
    "B0875AS": "Establishments: Veterinary (NOGA 75)",
    "B0877AS": "Establishments: Rental of movable goods (NOGA 77)",
    "B0878AS": "Establishments: Employment agencies (NOGA 78)",
    "B0879AS": "Establishments: Travel agencies (NOGA 79)",
    "B0880AS": "Establishments: Security services (NOGA 80)",
    "B0881AS": "Establishments: Building services, landscaping (NOGA 81)",
    "B0882AS": "Establishments: Other business services (NOGA 82)",
    "B0884AS": "Establishments: Public administration, defense (NOGA 84)",
    "B0885AS": "Establishments: Education (NOGA 85)",
    "B0886AS": "Establishments: Healthcare (NOGA 86)",
    "B0887AS": "Establishments: Residential care (NOGA 87)",
    "B0888AS": "Establishments: Social work (NOGA 88)",
    "B0890AS": "Establishments: Creative, arts, entertainment (NOGA 90)",
    "B0891AS": "Establishments: Libraries, museums, zoos (NOGA 91)",
    "B0892AS": "Establishments: Gambling, betting (NOGA 92)",
    "B0893AS": "Establishments: Sports, recreation (NOGA 93)",
    "B0894AS": "Establishments: Membership organisations (NOGA 94)",
    "B0895AS": "Establishments: Repair of computers/goods (NOGA 95)",
    "B0896AS": "Establishments: Other personal services (NOGA 96)",
    # --- Employees by NOGA division ---
    "B0801EMP": "Employees: Agriculture, hunting (NOGA 01)",
    "B0802EMP": "Employees: Forestry, logging (NOGA 02)",
    "B0803EMP": "Employees: Fishing, aquaculture (NOGA 03)",
    "B0805EMP": "Employees: Coal mining (NOGA 05)",
    "B0806EMP": "Employees: Oil and gas extraction (NOGA 06)",
    "B0807EMP": "Employees: Metal ore mining (NOGA 07)",
    "B0808EMP": "Employees: Other mining, quarrying (NOGA 08)",
    "B0809EMP": "Employees: Mining support services (NOGA 09)",
    "B0810EMP": "Employees: Food products (NOGA 10)",
    "B0811EMP": "Employees: Beverages (NOGA 11)",
    "B0812EMP": "Employees: Tobacco (NOGA 12)",
    "B0813EMP": "Employees: Textiles (NOGA 13)",
    "B0814EMP": "Employees: Wearing apparel (NOGA 14)",
    "B0815EMP": "Employees: Leather products (NOGA 15)",
    "B0816EMP": "Employees: Wood products (NOGA 16)",
    "B0817EMP": "Employees: Paper products (NOGA 17)",
    "B0818EMP": "Employees: Printing, media reproduction (NOGA 18)",
    "B0819EMP": "Employees: Coke, petroleum products (NOGA 19)",
    "B0820EMP": "Employees: Chemical products (NOGA 20)",
    "B0821EMP": "Employees: Pharmaceutical products (NOGA 21)",
    "B0822EMP": "Employees: Rubber and plastics (NOGA 22)",
    "B0823EMP": "Employees: Glass, ceramics, stone (NOGA 23)",
    "B0824EMP": "Employees: Basic metals (NOGA 24)",
    "B0825EMP": "Employees: Fabricated metals (NOGA 25)",
    "B0826EMP": "Employees: Computer, electronic, optical (NOGA 26)",
    "B0827EMP": "Employees: Electrical equipment (NOGA 27)",
    "B0828EMP": "Employees: Machinery (NOGA 28)",
    "B0829EMP": "Employees: Motor vehicles (NOGA 29)",
    "B0830EMP": "Employees: Other transport equipment (NOGA 30)",
    "B0831EMP": "Employees: Furniture (NOGA 31)",
    "B0832EMP": "Employees: Other manufactured goods (NOGA 32)",
    "B0833EMP": "Employees: Repair/installation of machinery (NOGA 33)",
    "B0835EMP": "Employees: Energy supply (NOGA 35)",
    "B0836EMP": "Employees: Water supply (NOGA 36)",
    "B0837EMP": "Employees: Sewerage (NOGA 37)",
    "B0838EMP": "Employees: Waste management, recycling (NOGA 38)",
    "B0839EMP": "Employees: Remediation (NOGA 39)",
    "B0841EMP": "Employees: Building construction (NOGA 41)",
    "B0842EMP": "Employees: Civil engineering (NOGA 42)",
    "B0843EMP": "Employees: Specialized construction (NOGA 43)",
    "B0845EMP": "Employees: Motor vehicle trade/repair (NOGA 45)",
    "B0846EMP": "Employees: Wholesale trade (NOGA 46)",
    "B0847EMP": "Employees: Retail trade (NOGA 47)",
    "B0849EMP": "Employees: Land transport (NOGA 49)",
    "B0850EMP": "Employees: Water transport (NOGA 50)",
    "B0851EMP": "Employees: Air transport (NOGA 51)",
    "B0852EMP": "Employees: Warehousing, transport support (NOGA 52)",
    "B0853EMP": "Employees: Postal, courier services (NOGA 53)",
    "B0855EMP": "Employees: Accommodation (NOGA 55)",
    "B0856EMP": "Employees: Food and beverage services (NOGA 56)",
    "B0858EMP": "Employees: Publishing (NOGA 58)",
    "B0859EMP": "Employees: Film, TV, music production (NOGA 59)",
    "B0860EMP": "Employees: Broadcasting (NOGA 60)",
    "B0861EMP": "Employees: Telecommunications (NOGA 61)",
    "B0862EMP": "Employees: IT services (NOGA 62)",
    "B0863EMP": "Employees: Information services (NOGA 63)",
    "B0864EMP": "Employees: Financial services (NOGA 64)",
    "B0865EMP": "Employees: Insurance, pensions (NOGA 65)",
    "B0866EMP": "Employees: Auxiliary financial services (NOGA 66)",
    "B0868EMP": "Employees: Real estate (NOGA 68)",
    "B0869EMP": "Employees: Legal, accounting (NOGA 69)",
    "B0870EMP": "Employees: Management consultancy (NOGA 70)",
    "B0871EMP": "Employees: Architecture, engineering (NOGA 71)",
    "B0872EMP": "Employees: R&D (NOGA 72)",
    "B0873EMP": "Employees: Advertising, market research (NOGA 73)",
    "B0874EMP": "Employees: Other professional services (NOGA 74)",
    "B0875EMP": "Employees: Veterinary (NOGA 75)",
    "B0877EMP": "Employees: Rental of movable goods (NOGA 77)",
    "B0878EMP": "Employees: Employment agencies (NOGA 78)",
    "B0879EMP": "Employees: Travel agencies (NOGA 79)",
    "B0880EMP": "Employees: Security services (NOGA 80)",
    "B0881EMP": "Employees: Building services, landscaping (NOGA 81)",
    "B0882EMP": "Employees: Other business services (NOGA 82)",
    "B0884EMP": "Employees: Public administration, defense (NOGA 84)",
    "B0885EMP": "Employees: Education (NOGA 85)",
    "B0886EMP": "Employees: Healthcare (NOGA 86)",
    "B0887EMP": "Employees: Residential care (NOGA 87)",
    "B0888EMP": "Employees: Social work (NOGA 88)",
    "B0890EMP": "Employees: Creative, arts, entertainment (NOGA 90)",
    "B0891EMP": "Employees: Libraries, museums, zoos (NOGA 91)",
    "B0892EMP": "Employees: Gambling, betting (NOGA 92)",
    "B0893EMP": "Employees: Sports, recreation (NOGA 93)",
    "B0894EMP": "Employees: Membership organisations (NOGA 94)",
    "B0895EMP": "Employees: Repair of computers/goods (NOGA 95)",
    "B0896EMP": "Employees: Other personal services (NOGA 96)",
    # --- FTE by NOGA division ---
    "B0801VZA": "FTE: Agriculture, hunting (NOGA 01)",
    "B0802VZA": "FTE: Forestry, logging (NOGA 02)",
    "B0803VZA": "FTE: Fishing, aquaculture (NOGA 03)",
    "B0805VZA": "FTE: Coal mining (NOGA 05)",
    "B0806VZA": "FTE: Oil and gas extraction (NOGA 06)",
    "B0807VZA": "FTE: Metal ore mining (NOGA 07)",
    "B0808VZA": "FTE: Other mining, quarrying (NOGA 08)",
    "B0809VZA": "FTE: Mining support services (NOGA 09)",
    "B0810VZA": "FTE: Food products (NOGA 10)",
    "B0811VZA": "FTE: Beverages (NOGA 11)",
    "B0812VZA": "FTE: Tobacco (NOGA 12)",
    "B0813VZA": "FTE: Textiles (NOGA 13)",
    "B0814VZA": "FTE: Wearing apparel (NOGA 14)",
    "B0815VZA": "FTE: Leather products (NOGA 15)",
    "B0816VZA": "FTE: Wood products (NOGA 16)",
    "B0817VZA": "FTE: Paper products (NOGA 17)",
    "B0818VZA": "FTE: Printing, media reproduction (NOGA 18)",
    "B0819VZA": "FTE: Coke, petroleum products (NOGA 19)",
    "B0820VZA": "FTE: Chemical products (NOGA 20)",
    "B0821VZA": "FTE: Pharmaceutical products (NOGA 21)",
    "B0822VZA": "FTE: Rubber and plastics (NOGA 22)",
    "B0823VZA": "FTE: Glass, ceramics, stone (NOGA 23)",
    "B0824VZA": "FTE: Basic metals (NOGA 24)",
    "B0825VZA": "FTE: Fabricated metals (NOGA 25)",
    "B0826VZA": "FTE: Computer, electronic, optical (NOGA 26)",
    "B0827VZA": "FTE: Electrical equipment (NOGA 27)",
    "B0828VZA": "FTE: Machinery (NOGA 28)",
    "B0829VZA": "FTE: Motor vehicles (NOGA 29)",
    "B0830VZA": "FTE: Other transport equipment (NOGA 30)",
    "B0831VZA": "FTE: Furniture (NOGA 31)",
    "B0832VZA": "FTE: Other manufactured goods (NOGA 32)",
    "B0833VZA": "FTE: Repair/installation of machinery (NOGA 33)",
    "B0835VZA": "FTE: Energy supply (NOGA 35)",
    "B0836VZA": "FTE: Water supply (NOGA 36)",
    "B0837VZA": "FTE: Sewerage (NOGA 37)",
    "B0838VZA": "FTE: Waste management, recycling (NOGA 38)",
    "B0839VZA": "FTE: Remediation (NOGA 39)",
    "B0841VZA": "FTE: Building construction (NOGA 41)",
    "B0842VZA": "FTE: Civil engineering (NOGA 42)",
    "B0843VZA": "FTE: Specialized construction (NOGA 43)",
    "B0845VZA": "FTE: Motor vehicle trade/repair (NOGA 45)",
    "B0846VZA": "FTE: Wholesale trade (NOGA 46)",
    "B0847VZA": "FTE: Retail trade (NOGA 47)",
    "B0849VZA": "FTE: Land transport (NOGA 49)",
    "B0850VZA": "FTE: Water transport (NOGA 50)",
    "B0851VZA": "FTE: Air transport (NOGA 51)",
    "B0852VZA": "FTE: Warehousing, transport support (NOGA 52)",
    "B0853VZA": "FTE: Postal, courier services (NOGA 53)",
    "B0855VZA": "FTE: Accommodation (NOGA 55)",
    "B0856VZA": "FTE: Food and beverage services (NOGA 56)",
    "B0858VZA": "FTE: Publishing (NOGA 58)",
    "B0859VZA": "FTE: Film, TV, music production (NOGA 59)",
    "B0860VZA": "FTE: Broadcasting (NOGA 60)",
    "B0861VZA": "FTE: Telecommunications (NOGA 61)",
    "B0862VZA": "FTE: IT services (NOGA 62)",
    "B0863VZA": "FTE: Information services (NOGA 63)",
    "B0864VZA": "FTE: Financial services (NOGA 64)",
    "B0865VZA": "FTE: Insurance, pensions (NOGA 65)",
    "B0866VZA": "FTE: Auxiliary financial services (NOGA 66)",
    "B0868VZA": "FTE: Real estate (NOGA 68)",
    "B0869VZA": "FTE: Legal, accounting (NOGA 69)",
    "B0870VZA": "FTE: Management consultancy (NOGA 70)",
    "B0871VZA": "FTE: Architecture, engineering (NOGA 71)",
    "B0872VZA": "FTE: R&D (NOGA 72)",
    "B0873VZA": "FTE: Advertising, market research (NOGA 73)",
    "B0874VZA": "FTE: Other professional services (NOGA 74)",
    "B0875VZA": "FTE: Veterinary (NOGA 75)",
    "B0877VZA": "FTE: Rental of movable goods (NOGA 77)",
    "B0878VZA": "FTE: Employment agencies (NOGA 78)",
    "B0879VZA": "FTE: Travel agencies (NOGA 79)",
    "B0880VZA": "FTE: Security services (NOGA 80)",
    "B0881VZA": "FTE: Building services, landscaping (NOGA 81)",
    "B0882VZA": "FTE: Other business services (NOGA 82)",
    "B0884VZA": "FTE: Public administration, defense (NOGA 84)",
    "B0885VZA": "FTE: Education (NOGA 85)",
    "B0886VZA": "FTE: Healthcare (NOGA 86)",
    "B0887VZA": "FTE: Residential care (NOGA 87)",
    "B0888VZA": "FTE: Social work (NOGA 88)",
    "B0890VZA": "FTE: Creative, arts, entertainment (NOGA 90)",
    "B0891VZA": "FTE: Libraries, museums, zoos (NOGA 91)",
    "B0892VZA": "FTE: Gambling, betting (NOGA 92)",
    "B0893VZA": "FTE: Sports, recreation (NOGA 93)",
    "B0894VZA": "FTE: Membership organisations (NOGA 94)",
    "B0895VZA": "FTE: Repair of computers/goods (NOGA 95)",
    "B0896VZA": "FTE: Other personal services (NOGA 96)",
}
# NOTE: STATENT also has ~340 establishment-by-size-class variables (B08xxKB1–KB4)
# per NOGA division. These are omitted for brevity but can be added if needed.
# Pattern: B08{NOGA:02}KB{1-4} — count of establishments by employee size class.

# ---------------------------------------------------------------------------
# Aggregation hints: how each variable should be aggregated to municipality level.
# "sum" for absolute counts/areas, "max" for categorical codes (use mode in practice).
# Variables not listed here default to "sum".
# ---------------------------------------------------------------------------
AGG_HINTS: dict[str, str] = {
    # STATPOP — all counts → sum (default)
    "HPI": "max",  # categorical class, not a count
    # SLS — all categorical codes → use mode (represented as "max" hint)
    **{k: "max" for k in SLS_VARIABLES},
}

# ---------------------------------------------------------------------------
# Dataset registry
# ---------------------------------------------------------------------------
DATASET_CATALOGS: dict[str, dict[str, str]] = {
    "statpop": STATPOP_VARIABLES,
    "bds": BDS_VARIABLES,
    "sls": SLS_VARIABLES,
    "statent": STATENT_VARIABLES,
}


# Maps SLS column name → SLS_CLASS_LABELS key for categorical composition.
# Used by aggregate_sls_composition() to know which label dict applies.
SLS_COMPOSITION_VARIABLE_LABEL_MAP: dict[str, str] = {
    "LU18_10": "LU_10",
    "AS18_17": "AS_17",
}


def get_selected_columns(dataset_key: str) -> list[str]:
    """Return variable codes from the catalog for a dataset.

    Only returns keys that are present (uncommented) in the corresponding dict.
    To exclude a variable, comment out its line in the dict above.
    """
    catalog = DATASET_CATALOGS.get(dataset_key)
    if catalog is None:
        raise ValueError(
            f"Unknown dataset key '{dataset_key}'. "
            f"Choose from: {list(DATASET_CATALOGS.keys())}"
        )
    return list(catalog.keys())
